items:
  -
    material: STONE
    price: 1
    count: 64
  -
    material: APPLE
    price: 1
    count: 8
  -
    material: GOLDEN_APPLE
    price: 100
    count: 3
  -
    material: BAMBOO
    price: 2
    count: 64